# mypy: disable-error-code="call-arg"
"""Adaptive-opponent streams: endogenous, closed-loop non-stationarity.

Every other stream in this package drifts *exogenously* (random walks,
scheduled switches).  These two streams make the non-stationarity come from a
learning process — the minimal form of the Alberta Plan's fourth
distinguishing feature ("the environment may include other intelligent agents
that behave differently in response to the agent's actions"):

- :class:`LearningOpponentStream` embeds an internal LMS learner (the
  "opponent") that adapts toward a hidden relation every step; the external
  learner's target is the opponent's *current prediction*.  The drift is a
  learning curve, not a random walk: fast early, slowing as the opponent
  converges, replayed from scratch at every opponent reset.  A meta-step-size
  learner tracking this stream exhibits the signature the Alberta Plan calls
  for: its step-sizes rise while the opponent is moving and decay as it
  converges.

- :class:`AdversarialPursuitStream` closes the loop on the learner itself:
  after seeing the learner's prediction, the target weights move (within a
  per-step budget) in exactly the direction that most increases the learner's
  error.  This is worst-case drift; a non-adaptive predictor's error grows
  without bound while continual learners remain bounded.  It uses an
  interactive two-phase protocol (:meth:`~AdversarialPursuitStream.emit` then
  :meth:`~AdversarialPursuitStream.resolve`) driven by
  :func:`run_pursuit_loop`, because the target of step ``t`` depends on the
  prediction at step ``t``.

Both are pure JAX and scan-compatible.
"""

from typing import Any

import chex
import jax
import jax.numpy as jnp
import jax.random as jr
from jax import Array
from jaxtyping import Float, Int, PRNGKeyArray

from alberta_framework.core.types import TimeStep


@chex.dataclass(frozen=True)
class LearningOpponentState:
    """State for :class:`LearningOpponentStream`.

    Attributes:
        key: Stream RNG key.
        step_count: Global step counter (drives opponent resets).
        w_star: Hidden true relation the opponent is learning.
        w_opp: The opponent's current weights (an LMS learner's state).
    """

    key: PRNGKeyArray
    step_count: Int[Array, ""]
    w_star: Float[Array, " feature_dim"]
    w_opp: Float[Array, " feature_dim"]


class LearningOpponentStream:
    """Predict another learner: targets are an adapting LMS opponent's outputs.

    Each step draws ``x ~ N(0, 1)``; the emitted target is the opponent's
    current prediction ``w_opp @ x`` (plus observation noise).  The opponent
    then takes its own LMS step toward the hidden relation ``w_star`` using an
    independent noisy sample.  Every ``reset_interval`` steps the opponent is
    replaced by a fresh one (weights back to zero), replaying the learning
    curve — recurring structure generated by learning dynamics themselves.
    """

    def __init__(
        self,
        feature_dim: int,
        opponent_step_size: float = 0.02,
        reset_interval: int = 4000,
        opponent_noise_std: float = 0.1,
        target_noise_std: float = 0.05,
        feature_std: float = 1.0,
    ):
        """Initialize the stream.

        Args:
            feature_dim: Dimension of observations and all weight vectors.
            opponent_step_size: LMS step-size of the internal opponent.
            reset_interval: Steps between opponent re-initializations
                (0 disables resets).
            opponent_noise_std: Noise on the samples the opponent learns from.
            target_noise_std: Observation noise on the emitted target.
            feature_std: Input standard deviation.
        """
        if feature_dim < 1:
            raise ValueError("feature_dim must be positive")
        if opponent_step_size <= 0.0:
            raise ValueError("opponent_step_size must be positive")
        if reset_interval < 0:
            raise ValueError("reset_interval must be non-negative")
        self._feature_dim = feature_dim
        self._opp_alpha = opponent_step_size
        self._reset_interval = reset_interval
        self._opp_noise_std = opponent_noise_std
        self._target_noise_std = target_noise_std
        self._feature_std = feature_std

    @property
    def feature_dim(self) -> int:
        """Return the dimension of observation vectors."""
        return self._feature_dim

    @property
    def reset_interval(self) -> int:
        """Steps between opponent re-initializations (0 = never)."""
        return self._reset_interval

    def init(self, key: Array) -> LearningOpponentState:
        """Initialize the hidden relation and a fresh (zero) opponent."""
        key, k_star = jr.split(key)
        w_star = jr.normal(k_star, (self._feature_dim,), dtype=jnp.float32)
        return LearningOpponentState(
            key=key,
            step_count=jnp.array(0, dtype=jnp.int32),
            w_star=w_star,
            w_opp=jnp.zeros((self._feature_dim,), dtype=jnp.float32),
        )

    def step(
        self, state: LearningOpponentState, idx: Array
    ) -> tuple[TimeStep, LearningOpponentState]:
        """Emit one (observation, opponent-prediction) pair, then let the opponent learn."""
        del idx
        key, k_x, k_tnoise, k_ox, k_onoise = jr.split(state.key, 5)

        # Opponent reset (fresh learner) on schedule.
        if self._reset_interval > 0:
            at_reset = state.step_count % self._reset_interval == 0
            w_opp = jnp.where(
                jnp.logical_and(at_reset, state.step_count > 0),
                jnp.zeros_like(state.w_opp),
                state.w_opp,
            )
        else:
            w_opp = state.w_opp

        # The external learner's task: predict the opponent's current output.
        x = self._feature_std * jr.normal(k_x, (self._feature_dim,), dtype=jnp.float32)
        noise = self._target_noise_std * jr.normal(k_tnoise, (), dtype=jnp.float32)
        target = jnp.dot(w_opp, x) + noise

        # The opponent takes its own LMS step on an independent sample.
        x_opp = self._feature_std * jr.normal(k_ox, (self._feature_dim,), dtype=jnp.float32)
        y_opp = jnp.dot(state.w_star, x_opp) + self._opp_noise_std * jr.normal(
            k_onoise, (), dtype=jnp.float32
        )
        opp_error = y_opp - jnp.dot(w_opp, x_opp)
        new_w_opp = w_opp + self._opp_alpha * opp_error * x_opp

        timestep = TimeStep(observation=x, target=jnp.atleast_1d(target))
        new_state = LearningOpponentState(
            key=key,
            step_count=state.step_count + 1,
            w_star=state.w_star,
            w_opp=new_w_opp,
        )
        return timestep, new_state


@chex.dataclass(frozen=True)
class AdversarialPursuitState:
    """State for :class:`AdversarialPursuitStream`.

    Attributes:
        key: Stream RNG key.
        step_count: Global step counter.
        w_adv: Current adversarial target weights.
        pending_x: Observation emitted by :meth:`AdversarialPursuitStream.emit`
            and awaiting :meth:`AdversarialPursuitStream.resolve`.
    """

    key: PRNGKeyArray
    step_count: Int[Array, ""]
    w_adv: Float[Array, " feature_dim"]
    pending_x: Float[Array, " feature_dim"]


class AdversarialPursuitStream:
    """Budgeted worst-case drift: the target runs away from the learner.

    Interactive protocol per step: :meth:`emit` produces the observation;
    the learner predicts; :meth:`resolve` computes the target from the
    current adversarial weights, then moves those weights a step of norm
    ``drift_budget`` in the direction that most increases the learner's
    squared error on the just-seen observation (the normalized gradient
    ``err * x / ||x||``).  A frozen predictor is pushed away linearly;
    continual learners stay within a bounded pursuit distance.
    """

    def __init__(
        self,
        feature_dim: int,
        drift_budget: float = 0.02,
        noise_std: float = 0.05,
        feature_std: float = 1.0,
    ):
        """Initialize the stream.

        Args:
            feature_dim: Dimension of observations and target weights.
            drift_budget: Per-step L2 norm of the adversarial weight move.
            noise_std: Observation noise on targets.
            feature_std: Input standard deviation.
        """
        if feature_dim < 1:
            raise ValueError("feature_dim must be positive")
        if drift_budget < 0.0:
            raise ValueError("drift_budget must be non-negative")
        self._feature_dim = feature_dim
        self._budget = drift_budget
        self._noise_std = noise_std
        self._feature_std = feature_std

    @property
    def feature_dim(self) -> int:
        """Return the dimension of observation vectors."""
        return self._feature_dim

    def init(self, key: Array) -> AdversarialPursuitState:
        """Initialize adversarial weights ~ N(0, 1)."""
        key, k_w = jr.split(key)
        w_adv = jr.normal(k_w, (self._feature_dim,), dtype=jnp.float32)
        return AdversarialPursuitState(
            key=key,
            step_count=jnp.array(0, dtype=jnp.int32),
            w_adv=w_adv,
            pending_x=jnp.zeros((self._feature_dim,), dtype=jnp.float32),
        )

    def emit(self, state: AdversarialPursuitState) -> tuple[Array, AdversarialPursuitState]:
        """Draw and store the observation for this step."""
        key, k_x = jr.split(state.key)
        x = self._feature_std * jr.normal(k_x, (self._feature_dim,), dtype=jnp.float32)
        return x, AdversarialPursuitState(
            key=key,
            step_count=state.step_count,
            w_adv=state.w_adv,
            pending_x=x,
        )

    def resolve(
        self, state: AdversarialPursuitState, prediction: Array
    ) -> tuple[Array, AdversarialPursuitState]:
        """Produce the target for the pending observation, then move adversarially.

        Args:
            state: Stream state after :meth:`emit`.
            prediction: The learner's prediction for the pending observation.

        Returns:
            ``(target, new_state)``; the returned target is computed from the
            *pre-move* weights, so the adversary reacts to the learner but
            never rewrites history.
        """
        key, k_noise = jr.split(state.key)
        x = state.pending_x
        noise = self._noise_std * jr.normal(k_noise, (), dtype=jnp.float32)
        target = jnp.dot(state.w_adv, x) + noise

        # Move w_adv within budget along the gradient of the learner's squared
        # error: d/dw (w @ x - p)^2 proportional to (w @ x - p) * x.
        err = jnp.dot(state.w_adv, x) - jnp.squeeze(prediction)
        direction = err * x
        norm = jnp.linalg.norm(direction)
        unit = jnp.where(norm > 1e-8, direction / jnp.maximum(norm, 1e-8), 0.0)
        new_w = state.w_adv + self._budget * unit

        new_state = AdversarialPursuitState(
            key=key,
            step_count=state.step_count + 1,
            w_adv=new_w,
            pending_x=x,
        )
        return jnp.atleast_1d(target), new_state


def run_pursuit_loop(
    learner: Any,
    stream: AdversarialPursuitStream,
    num_steps: int,
    key: Array,
    learner_state: Any = None,
    frozen: bool = False,
) -> tuple[Any, Array]:
    """Run a learner against :class:`AdversarialPursuitStream`.

    Args:
        learner: Any learner exposing ``init(feature_dim)``,
            ``predict(state, observation)``, and
            ``update(state, observation, target)`` (LinearLearner-compatible).
        stream: The pursuit stream.
        num_steps: Number of interactive steps.
        key: Stream initialization key.
        learner_state: Optional initial learner state.
        frozen: When True the learner never updates — the non-adaptive
            control whose error the adversary drives upward without bound.

    Returns:
        ``(final_learner_state, squared_errors)`` with squared errors of
        shape ``(num_steps,)``.
    """
    l_state = learner.init(stream.feature_dim) if learner_state is None else learner_state
    s_state = stream.init(key)

    def step_fn(
        carry: tuple[Any, AdversarialPursuitState],
        _: Array,
    ) -> tuple[tuple[Any, AdversarialPursuitState], Array]:
        l_st, s_st = carry
        x, s_st = stream.emit(s_st)
        prediction = learner.predict(l_st, x)
        target, s_st = stream.resolve(s_st, prediction)
        sq_error = (jnp.squeeze(target) - jnp.squeeze(prediction)) ** 2
        if not frozen:
            result = learner.update(l_st, x, target)
            l_st = result.state
        return (l_st, s_st), sq_error

    (final_state, _), sq_errors = jax.lax.scan(step_fn, (l_state, s_state), jnp.arange(num_steps))
    return final_state, sq_errors
